baseURL = 'https://blog.poleprediction.com'
languageCode = 'en-us'
title = "Allanderek's blog"
theme = 'papermod'
mainSections = ["posts"]


[menu]
  [[menu.main]]
    name = "RSS Feed"
    url = "/rss/index.xml"
    weight = 100  # Higher weight will place it at the end of the menu
    

[pagination]
  disableAliases = false
  pagerSize = 100
  path = 'page'

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    isPlainText = false
    rel = "alternate"
    isHTML = false
    noUgly = true
    permalinkable = false
    path = "/rss"

[outputs]
  home = ["HTML", "RSS", "ATOM"]
